version: '0.1'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./app:/code/app
  gpcon:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      API_KEY: ${API_KEY}
